### ISSUE TITLE
Error: site is required

### ISSUE THREAD

**Issue by howardabrams** [vermiculus/sx.el#220] opened 2015-01-08 06:35 UTC
Kicked of a `sx-authenticate` and got that working, and next, I run
`sx-tab-newest`, and it successfully got my favorite groups. I
selected "emacs" (obviously), and it comes up with this error:

    Contacting host: api.stackexchange.com:443
    progn: Request failed: (nil) [400 bad_parameter] "site is required"

I'll see if I can debug it more later, but if I am doing something
wrong, I would appreciate the pointer, as I'm looking forward to
playing with this fun toy.

**Comment by vermiculus** [comment] 2015-01-08 13:09
I can't seem to reproduce the issue on the current `master` from a fresh emacs – can you give us the stacktrace with `toggle-debug-on-error`?

**Comment by Bruce-Connor** [comment] 2015-01-08 14:00
Also, are you using the latest version from Melpa, or the (not so) stable 0.1 version from Melpa-stable?

**Comment by kcandrews** [comment] 2015-01-08 14:18
Hi, I'm getting the same "site is required" error out of box. Below is the `*Backtrace*` after enabling `toggle-debug-on-error` and redacting what looked like my authentication key:

```
Debugger entered--Lisp error: (error "Request failed: (nil) [400 bad_parameter] \"site is required\"")
  signal(error ("Request failed: (nil) [400 bad_parameter] \"site is required\""))
  error("Request failed: (%s) [%i %s] %S" nil 400 "bad_parameter" "site is required")
  sx-request-make("me/favorites" ((pagesize . 100) (page) (filter . "MAGIC-KEY-REDACTED")) get sx-request-response-get-items)
  sx-method-call(me :submethod favorites :site nil :filter ((question\.question_id \.backoff \.error_id \.error_message \.error_name \.has_more \.items \.page \.page_size \.quota_max \.quota_remaining \.total) nil none) :auth t)
  sx-favorites--retrieve-favorites(nil)
  sx-favorites--update-site-favorites(nil)
  mapc(sx-favorites--update-site-favorites (nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil))
  sx-favorites-update()
  sx-favorites--initialize()
  run-hooks(sx-init--internal-hook sx-init-hook)
  sx-initialize()
  sx-tab-frontpage(nil "emacs")
  call-interactively(sx-tab-frontpage record nil)
  command-execute(sx-tab-frontpage record)
  helm-M-x()
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)
```

**Comment by vermiculus** [comment] 2015-01-08 14:20
Well here's the culprit -- I'm not sure why this is happening, though

```
  sx-method-call(me :submethod favorites :site nil :filter ((question\.question_id ...) nil none) :auth t)
```

**Comment by Bruce-Connor** [comment] 2015-01-08 15:20
Yes, it looks like `sx-network-user-sites` is returning a list of nils.

Another problem, which is won't fix this issue but will workaround it (and we should do it anyway), is that we're fetching a list of favorite questions for all sites at initialization. We never use that list, so there's no need to do that.

**Comment by Bruce-Connor** [comment] 2015-01-08 15:53
I confirm I canreproduce this by invalidating my cache.

**Comment by Bruce-Connor** [comment] 2015-01-08 16:07
To fix this, we just need to add `site_url` to `sx-site-browse-filter`

**Closed** 2015-01-08 16:18 UTC
Labels: bug

**Comment by vermiculus** [comment] 2015-01-08 16:35
@howardabrams @kcandrews -- Can you confirm this has fixed the issue? The next MELPA build should be any minute now, but may be up to an hour away.

**Comment by kcandrews** [comment] 2015-01-08 17:01
Just updated from MELPA (20150108.815). I see `site_url` in `(defconst sx-site-browse-filter ...` in `sx-site.el` so I think this is the latest version? I'm still getting the error, however. The `*Backtrace*` looks identical as far as I can tell.

```
Debugger entered--Lisp error: (error "Request failed: (nil) [400 bad_parameter] \"site is required\"")
  signal(error ("Request failed: (nil) [400 bad_parameter] \"site is required\""))
  error("Request failed: (%s) [%i %s] %S" nil 400 "bad_parameter" "site is required")
  sx-request-make("me/favorites" ((pagesize . 100) (page) (filter . "MAGIC-KEY-REDACTED")) get sx-request-response-get-items)
  sx-method-call(me :submethod favorites :site nil :filter ((question\.question_id \.backoff \.error_id \.error_message \.error_name \.has_more \.items \.page \.page_size \.quota_max \.quota_remaining \.total) nil none) :auth t)
  sx-favorites--retrieve-favorites(nil)
  sx-favorites--update-site-favorites(nil)
  mapc(sx-favorites--update-site-favorites (nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil))
  sx-favorites-update()
  sx-favorites--initialize()
  run-hooks(sx-init--internal-hook sx-init-hook)
  sx-initialize()
  sx-tab-newest(nil "emacs")
  call-interactively(sx-tab-newest record nil)
  command-execute(sx-tab-newest record)
  helm-M-x()
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)
```

**Comment by Bruce-Connor** [comment] 2015-01-08 18:01
Do `sx-cache-invalidate-all`, and try again.

**Comment by howardabrams** [comment] 2015-01-08 18:01
That worked! Thanks a lot for the quick turn-around.

**Comment by kcandrews** [comment] 2015-01-08 19:55
Indeed. Running Bruce's command fixed the issue.
